from pathlib import Path

ROOT_PATH = Path(__file__).resolve().parent.parent
_NIVA_DIR = ROOT_PATH / "niva"
AUX = ROOT_PATH / "aux"

SOURCE = _NIVA_DIR / "EswmRaster.tif"
FILLED_CLIPPED_COG = _NIVA_DIR / "boelgeeksponering_norge_2004_25833.tif"
"""Raster after filling and clipping, used for direct vector translation"""
FILLED_COG = _NIVA_DIR / "EswmRaster_filled_cog.tif"
"""Raster after filling with two pixel overlap, used for marint naturkart and detailed vector dataset"""
CLASSIFIED_CLIPPED = _NIVA_DIR / "boelgeeksponering_nin_basistrinn_norge_2004_25833.tif"
"""Classified clipped raster"""
CLASSIFIED = _NIVA_DIR / "EswmRaster_classified.tif"
"""Classified raster"""
CLASSIFIED_SIEVED = _NIVA_DIR / "EswmRaster_classified_sieved.tif"
"""Sieved classified raster"""
RAW_VECTOR = _NIVA_DIR / "Eswm_classified_raw.gpkg"
"""Raw classified vector"""
CLEANED_VECTOR = _NIVA_DIR / "Eswm_classified_merged.gpkg"
"""Raw vector with small polygons merged into neighbours"""
LAND_CLIPPED_VECTOR = _NIVA_DIR / "Eswm_clipped.gpkg"
"""Clipped vector"""
SEA_CLIPPED_VECTOR = _NIVA_DIR / "EswmVectorClasses.gpkg"
"""Classified vector dataset clipped to kartverktes kystlinje"""
CHECKPOINT_FILE = _NIVA_DIR / "Eswm_land_subtract_checkpoint.gpkg"
"""Checkpoint for land subtraction"""
LAND = AUX / "Basisdata_Landareal.gpkg"
"""Land polygons for subtraction from Kartverket"""
DIRECT_VECTOR = _NIVA_DIR / "boelgeeksponering_nin_basistrinn_norge_2004_25833.gpkg"
"""Directly mapped vector from EswmRasterFillClasses.tif"""