from pathlib import Path

ROOT_PATH = Path(__file__).resolve().parent.parent
_NIVA_DIR = ROOT_PATH / "niva"
AUX = ROOT_PATH / "aux"

SOURCE = _NIVA_DIR / "EswmRaster.tif"
FILLED_CLIPPED_COG = _NIVA_DIR / "EswmRaster_filled_clipped_cog.tif"
"""Raster after filling and clipping"""
FILLED_COG = _NIVA_DIR / "EswmRaster_filled_cog.tif"
"""Raster after filling used for creating vector"""
CLASSIFIED_CLIPPED = _NIVA_DIR / "EswmRaster_classified_clipped_cog.tif"
"""Classified clipped raster"""
CLASSIFIED = _NIVA_DIR / "EswmRaster_classified.tif"
"""Classified raster"""
CLASSIFIED_SIEVED = _NIVA_DIR / "EswmRaster_classified_sieved.tif"
"""Sieved classified raster"""
RAW_VECTOR = _NIVA_DIR / "Eswm_classified_raw.gpkg"
"""Raw classified vector"""
CLEANED_VECTOR = _NIVA_DIR / "Eswm_classified_merged.gpkg"
"""Raw vector with small polygons merged into neighbours"""
LAND_CLIPPED_VECTOR = _NIVA_DIR / "Eswm_clipped.gpkg"
"""Clipped vector"""
FIN = _NIVA_DIR / "Eswm_mapped_classified.gpkg"
"""Final mapped/classified vector"""
CHECKPOINT_FILE = _NIVA_DIR / "Eswm_land_subtract_checkpoint.gpkg"
"""Checkpoint for land subtraction"""
LAND = AUX / "Basisdata_Landareal_padded.gpkg"
"""Land polygons for subtraction from field"""
GRUNNLINJE = AUX / "grunnlinje_1nautisk.gpkg"
"""Baseline grunnlinje polygon inside norway"""